Repository LIKELION-Android-Bootcamp-4th/AOS-04-officeShoppingMall, pull requests merged in 2025-07, with the labels that each got.

#9 Develop
  lib/AppRouter.dart
  lib/core/constants/app_colors.dart
  lib/core/constants/app_constants.dart
  lib/core/constants/app_routes.dart
  lib/main.dart
  pubspec.lock
Labels: enhancement

#11 [Bug] 커스텀 앱바 아이콘 오류
  lib/core/widgets/custom_app_bar.dart
  lib/main.dart
  pubspec.yaml
Labels: bug

#15 refactor appBar 생성자 매개변수 추가
  lib/core/constants/app_routes.dart
  lib/core/widgets/custom_app_bar.dart
Labels: documentation

#17 [Feature] Swagger와 통신하는 Api 클라이언트 구현
  lib/core/constants/api_endpoints.dart
  lib/core/constants/app_routes.dart
  lib/core/services/api_client.dart
  lib/core/services/auth_service.dart
  lib/feature/home/ui/HomeScreen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement

#20 [Feature] 앱 테마 설정
  lib/core/constants/app_colors.dart
  lib/core/theme/app_colors.dart
  lib/core/theme/theme.dart
  lib/core/widgets/custom_app_bar.dart
  lib/main.dart
Labels: enhancement

#25 [Feature] 좋아요 화면 구현
  lib/app_router.dart
  lib/core/constants/api_endpoints.dart
  lib/core/constants/app_constants.dart
  lib/core/constants/app_routes.dart
  lib/core/services/auth_service.dart
  lib/core/widgets/bottom_navigation.dart
  lib/feature/auth/ui/auth_header.dart
  lib/feature/auth/ui/login_form.dart
  lib/feature/auth/ui/login_goSignup.dart
  lib/feature/auth/ui/login_screen.dart
  lib/feature/auth/ui/signup_form.dart
  lib/feature/auth/ui/signup_screen.dart
  lib/feature/home/ui/home_content_products.dart
  lib/feature/home/ui/home_screen.dart
  lib/feature/preference/ui/preference_content_count_text.dart
  lib/feature/preference/ui/preference_content_list.dart
  lib/feature/preference/ui/preference_screen.dart
  lib/feature/product/ui/product_item.dart
  lib/feature/product/ui/product_list_content.dart
  lib/feature/product/ui/product_list_screen.dart
  lib/main.dart
Labels: enhancement

#29 [Feature] 앱 아이콘 및 앱 이름 적용
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/icon/ic_launcher.png
  images/app_icon.jpg
  ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/114.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/120.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/180.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/29.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/40.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/57.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/58.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/60.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/80.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/87.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Info.plist
  lib/core/theme/theme.dart
  lib/core/widgets/custom_app_bar.dart
  lib/feature/auth/ui/auth_header.dart
  lib/feature/home/ui/home_content_banner.dart
  lib/feature/home/ui/home_content_products.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#30 [Feature] 내비게이션바 상태 Provider 구현
  lib/core/providers/bottom_nav_provider.dart
  lib/core/widgets/bottom_navigation.dart
  lib/main.dart
Labels: enhancement

#33 [Feature] 회원가입 기능 추가
  lib/core/constants/api_endpoints.dart
  lib/core/services/auth_service.dart
  lib/feature/auth/ui/signup_form.dart
  lib/feature/home/ui/search_recent_keyword.dart
Labels: enhancement

#37 [Feature] 장바구니/주문내역 UI 구현
  lib/app_router.dart
  lib/core/constants/app_routes.dart
  lib/feature/cart/data/product.dart
  lib/feature/cart/data/product_list.dart
  lib/feature/cart/data/product_list_item.dart
  lib/feature/cart/data/product_provider.dart
  lib/feature/cart/ui/DeliveryMain.dart
  lib/feature/cart/ui/DeliveryScreen.dart
  lib/feature/cart/ui/cart_screen.dart
  lib/feature/cart/ui/delivery_navigation.dart
  lib/feature/cart/ui/delivery_screen.dart
  lib/feature/cart/ui/order_detail_screen.dart
  lib/main.dart
Labels: enhancement

#38 [Refactor] 앱바 및 다이어로그 리팩터링
  lib/core/widgets/app_bar_actions.dart
  lib/feature/auth/ui/login_screen.dart
  lib/feature/auth/ui/signup_screen.dart
  lib/feature/category/ui/category_screen.dart
  lib/feature/home/ui/home_content_products.dart
  lib/feature/home/ui/home_screen.dart
  lib/feature/mypage/ui/mypage_screen.dart
  lib/feature/preference/ui/preference_content_list.dart
  lib/feature/preference/ui/preference_screen.dart
Labels: enhancement

#39 [Feature] Api 엔드포인트 추가 및 변경
  lib/core/constants/api_endpoints.dart
  lib/core/services/api_client.dart
  lib/core/services/auth_service.dart
Labels: enhancement

#40 [Refactor] cart 관련 화면 전체 리팩터링
  lib/feature/cart/data/product.dart
  lib/feature/cart/data/product_list.dart
  lib/feature/cart/data/product_list_item.dart
  lib/feature/cart/data/product_provider.dart
  lib/feature/cart/ui/DeliveryMain.dart
  lib/feature/cart/ui/DeliveryScreen.dart
  lib/feature/cart/ui/cart_screen.dart
  lib/feature/cart/ui/delivery_navigation.dart
  lib/feature/cart/ui/delivery_screen.dart
  lib/feature/cart/ui/order_detail_screen.dart
Labels: Refactor

#45 [feature] 로그인 상태 추가
  lib/feature/auth/bloc/auth_provider.dart
  lib/feature/auth/ui/login_form.dart
  lib/main.dart
Labels: enhancement

#46 [feature] 검색화면 UI
  lib/app_router.dart
  lib/core/constants/app_routes.dart
  lib/feature/home/ui/home_screen.dart
  lib/feature/home/ui/search_recent_keyword.dart
  lib/feature/search/ui/search_content_searchbar.dart
  lib/feature/search/ui/search_popular.dart
  lib/feature/search/ui/search_recent_keyword.dart
  lib/feature/search/ui/search_screen.dart
  lib/main.dart
Labels: enhancement

#48 [Feature] 설정 화면 ui 구현
  devtools_options.yaml
  lib/app_router.dart
  lib/core/constants/api_endpoints.dart
  lib/core/constants/app_constants.dart
  lib/core/constants/app_routes.dart
  lib/core/data/services/api_client.dart
  lib/core/data/services/auth_service.dart
  lib/core/providers/bottom_nav_provider.dart
  lib/core/theme/app_colors.dart
  lib/core/theme/theme.dart
  lib/core/widgets/app_bar/app_bar_actions.dart
  lib/core/widgets/app_bar/custom_app_bar.dart
  lib/core/widgets/app_bar_actions.dart
  lib/core/widgets/custom_tab_bar.dart
  lib/feature/auth/ui/auth_header.dart
  lib/feature/auth/ui/login_form.dart
  lib/feature/auth/ui/login_screen.dart
  lib/feature/auth/ui/signup_form.dart
  lib/feature/auth/ui/signup_screen.dart
  lib/feature/cart/data/product.dart
  lib/feature/cart/ui/cart_screen.dart
  lib/feature/category/data/category_section.dart
  lib/feature/category/ui/category_screen.dart
  lib/feature/home/ui/home_screen.dart
  lib/feature/mypage/ui/mypage_content_menu_list.dart
  lib/feature/mypage/ui/mypage_content_user_card.dart
  lib/feature/mypage/ui/mypage_screen.dart
  lib/feature/notification/data/app_notification.dart
  lib/feature/notification/ui/notification_navigation.dart
  lib/feature/notification/ui/notification_screen.dart
  lib/feature/order/ui/order_bottom.dart
  lib/feature/order/ui/order_complete_content.dart
  lib/feature/order/ui/order_complete_screen.dart
  lib/feature/order/ui/order_content.dart
  lib/feature/order/ui/order_screen.dart
  lib/feature/preference/ui/preference_screen.dart
  lib/feature/product/ui/product_button.dart
  lib/feature/product/ui/product_content_container.dart
  lib/feature/product/ui/product_description_content.dart
  lib/feature/product/ui/product_detail_content.dart
  lib/feature/product/ui/product_detail_screen.dart
  lib/feature/product/ui/product_item.dart
  lib/feature/product/ui/product_list_content.dart
  lib/feature/product/ui/product_list_screen.dart
  lib/feature/product/ui/product_navigation.dart
  lib/feature/product/ui/product_review_content.dart
  lib/feature/product/ui/product_tab.dart
  lib/feature/search/ui/search_content_searchbar.dart
  lib/feature/search/ui/search_popular.dart
  lib/feature/search/ui/search_recent_keyword.dart
  lib/feature/search/ui/search_screen.dart
  lib/feature/setting/ui/noti_setting_tab.dart
  lib/feature/setting/ui/setting_screen.dart
  lib/feature/setting/ui/user_info_tab.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#50 [Feature] 비밀번호 변경 화면 구현
  lib/app_router.dart
  lib/core/constants/app_routes.dart
  lib/feature/setting/ui/pw_setting.dart
Labels: enhancement

#55 [Feature] 배송지 설정 화면 구현
  lib/app_router.dart
  lib/core/constants/app_routes.dart
  lib/feature/setting/ui/dest_setting_screen.dart
  lib/feature/setting/ui/user_info_tab.dart
Labels: enhancement

#53 [Feature] 리뷰 작성 페이지 UI 구현
  lib/app_router.dart
  lib/core/constants/app_routes.dart
  lib/feature/review/ui/add_review_content.dart
  lib/feature/review/ui/add_review_screen.dart
Labels: enhancement

#59 [Refactor] 일부화면 앱바의 leading 제거
  lib/core/widgets/app_bar/custom_app_bar.dart
  lib/feature/category/ui/category_screen.dart
  lib/feature/mypage/ui/mypage_screen.dart
  lib/feature/preference/ui/preference_screen.dart
Labels: Refactor

#61 [Refactor] 상품 리스트 UI 수정
  lib/core/constants/app_routes.dart
  lib/feature/cart/data/product_list_item.dart
  lib/feature/cart/ui/cart_screen.dart
  lib/feature/cart/ui/delivery_navigation.dart
  lib/feature/cart/ui/order_detail_screen.dart
  lib/feature/review/data/review_list.dart
  lib/feature/review/ui/review_screen.dart
Labels: Refactor

#62 Feature/login state
  lib/app_router.dart
  lib/core/data/models/signup_response.dart
  lib/feature/auth/data/auth_service.dart
  lib/feature/auth/presentation/login_screen.dart
  lib/feature/auth/presentation/signup_screen.dart
  lib/feature/auth/presentation/viewmodel/auth_view_model.dart
  lib/feature/auth/presentation/widgets/auth_header.dart
  lib/feature/auth/presentation/widgets/login_form.dart
  lib/feature/auth/presentation/widgets/login_goSignup.dart
  lib/feature/auth/presentation/widgets/signup_form.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#65 [Feature] api 엔드포인트 추가 및 수정
  lib/core/constants/api_endpoints.dart
  lib/feature/mypage/data/mypage_service.dart
Labels: enhancement

#69 [Feature] 리뷰 확인 화면 UI 추가 및 수정
  lib/feature/review/presentation/review_detail_screen.dart
  lib/feature/review/presentation/review_screen.dart
  lib/feature/review/presentation/widgets/add_review_content.dart
  lib/feature/review/presentation/widgets/review_writable_tab.dart
  lib/feature/review/presentation/widgets/review_written_tab.dart
Labels: enhancement

#70 [Feature] Api 관련 변경
  lib/app_router.dart
  lib/core/constants/api_endpoints.dart
  lib/core/constants/app_constants.dart
  lib/core/data/models/dto/user_dto.dart
  lib/core/data/models/user_dto.dart
  lib/core/data/network/api_client.dart
  lib/core/data/network/interceptors/auth_interceptor.dart
  lib/core/data/network/interceptors/logging_interceptor.dart
  lib/core/data/network/secure_storage.dart
  lib/core/widgets/app_bar/custom_app_bar.dart
  lib/feature/auth/data/auth_service.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#71 [Feature] 비밀번호 변경 api 연동
  lib/feature/auth/domain/auth_repository.dart
  lib/feature/mypage/data/mypage_service.dart
  lib/feature/mypage/domain/mypage_repository.dart
  lib/feature/mypage/mypage_module.dart
  lib/feature/mypage/presentation/viewmodel/mypage_viewmodel.dart
  lib/feature/setting/data/pw_setting_request.dart
  lib/feature/setting/data/pw_setting_response.dart
  lib/feature/setting/data/setting_service.dart
  lib/feature/setting/domain/setting_repository.dart
  lib/feature/setting/presentation/viewmodel/setting_view_model.dart
  lib/feature/setting/presentation/widgets/pw_setting.dart
  lib/feature/setting/presentation/widgets/user_info_tab.dart
  lib/feature/setting/setting_module.dart
  lib/main.dart
Labels: enhancement

#72 [Feature] setting 화면 네트워킹
  lib/core/data/models/entity/user.dart
  lib/feature/mypage/data/mypage_service.dart
  lib/feature/mypage/domain/mypage_repository.dart
  lib/feature/mypage/presentation/viewmodel/mypage_viewmodel.dart
  lib/feature/mypage/presentation/widgets/mypage_content_user_card.dart
  lib/feature/setting/data/setting_address.dart
  lib/feature/setting/data/setting_service.dart
  lib/feature/setting/domain/setting_repository.dart
  lib/feature/setting/presentation/dest_setting_screen.dart
  lib/feature/setting/presentation/setting_screen.dart
  lib/feature/setting/presentation/viewmodel/setting_view_model.dart
  lib/feature/setting/presentation/viewmodel/setting_viewmodel.dart
  lib/feature/setting/presentation/widgets/pw_setting.dart
  lib/feature/setting/presentation/widgets/user_info_tab.dart
  lib/feature/setting/setting_module.dart
Labels: enhancement

#77 [Fix] setting 관련 fix
  lib/core/data/models/dto/user_dto.dart
  lib/core/data/models/entity/user.dart
  lib/feature/setting/presentation/widgets/user_info_tab.dart
Labels: Refactor

#80 [Feature] category 타이틀 탭 이벤트 구현
  lib/feature/category/presentation/widgets/category_content_list.dart
  lib/feature/home/presentation/widgets/home_content_products.dart
  lib/feature/preference/presentation/widgets/preference_content_list.dart
Labels: enhancement

#81 [Feature] home 스크린 카테고리 연결
  images/category_rect_deskterior.png
  images/category_rect_office_supplies.png
  images/category_rect_peripheral.png
  images/category_rect_supplement.jpg
  lib/feature/home/data/home_category_item.dart
  lib/feature/home/presentation/widgets/home_content_category.dart
Labels: enhancement

#84 [Refactor] product dto 수정
  lib/core/data/models/dto/cart_dto.dart
  lib/core/data/models/dto/order_dto.dart
  lib/core/data/models/dto/product.dart
  lib/core/data/models/dto/product_dto.dart
  lib/feature/order/presentation/order_screen.dart
  lib/feature/order/presentation/widgets/order_content.dart
  lib/feature/product/data/product_service.dart
  lib/feature/product/domain/product_repository_impl.dart
  lib/feature/product/domain/repository/product_repository.dart
  lib/feature/product/presentation/viewmodel/product_list_viewmodel.dart
  lib/feature/product/presentation/viewmodel/product_viewmodel.dart
  lib/feature/product/presentation/widgets/product_description_content.dart
  lib/feature/product/presentation/widgets/product_detail_content.dart
  lib/feature/product/presentation/widgets/product_item.dart
Labels: enhancement

#86 [Refactor] 폴더 정리 및 파일명 변경
  lib/app_router.dart
  lib/feature/cart/presentation/cart_main_screen.dart
  lib/feature/cart/presentation/widgets/cart_tab.dart
  lib/feature/order/data/order_list.dart
  lib/feature/order/data/order_list_item.dart
  lib/feature/order/data/order_provider.dart
  lib/feature/order/data/order_service.dart
  lib/feature/order/presentation/order_detail_screen.dart
  lib/feature/order/presentation/widgets/order_delivered_tab.dart
  lib/feature/order/presentation/widgets/order_paid_tab.dart
  lib/feature/order/presentation/widgets/order_shipping_tab.dart
  lib/feature/payment/payment_complete_screen.dart
  lib/feature/payment/payment_screen.dart
  lib/feature/payment/presentaion/widgets/payment_bottom.dart
  lib/feature/payment/presentaion/widgets/payment_complete_content.dart
  lib/feature/payment/presentaion/widgets/payment_content.dart
  lib/feature/review/presentation/widgets/review_writable_tab.dart
  lib/main.dart
Labels: Refactor

#90 [Feature] preference 네트워킹 성공
  lib/core/utils/extension.dart
  lib/feature/preference/data/preference_service.dart
  lib/feature/preference/domain/preference_repository.dart
  lib/feature/preference/preference_module.dart
  lib/feature/preference/presentation/viewmodel/preference_viewmodel.dart
  lib/feature/preference/presentation/widgets/preference_content_count_text.dart
  lib/feature/preference/presentation/widgets/preference_content_list.dart
  lib/main.dart
Labels: enhancement

#89 [Feature] 주문내역/배송 탭 api 연동
  lib/core/data/models/dto/order_dto.dart
  lib/feature/cart/data/cart_list_item.dart
  lib/feature/cart/presentation/cart_main_screen.dart
  lib/feature/cart/presentation/widgets/cart_tab.dart
  lib/feature/order/data/order_list.dart
  lib/feature/order/data/order_list_item.dart
  lib/feature/order/data/order_provider.dart
  lib/feature/order/data/order_service.dart
  lib/feature/order/domain/order_repository_impl.dart
  lib/feature/order/domain/repository/order_repository.dart
  lib/feature/order/order_module.dart
  lib/feature/order/presentation/order_detail_screen.dart
  lib/feature/order/presentation/viewmodel/order_viewmodel.dart
  lib/feature/order/presentation/widgets/order_delivered_tab.dart
  lib/feature/order/presentation/widgets/order_paid_tab.dart
  lib/feature/order/presentation/widgets/order_shipping_tab.dart
  lib/feature/review/presentation/widgets/review_writable_tab.dart
  lib/main.dart
Labels: enhancement

#92 [Feature] setting 프로필 업로드 관련
  lib/core/data/models/dto/user_dto.dart
  lib/core/data/models/entity/user.dart
  lib/feature/mypage/presentation/widgets/mypage_content_user_card.dart
  lib/feature/setting/data/setting_service.dart
  lib/feature/setting/domain/setting_repository.dart
  lib/feature/setting/presentation/setting_screen.dart
  lib/feature/setting/presentation/viewmodel/setting_viewmodel.dart
  lib/feature/setting/presentation/widgets/user_info_tab.dart
Labels: enhancement

#94 [Feature] 상품 평점 항목 나열 및 상세 화면 추가
  lib/app_router.dart
  lib/core/constants/app_routes.dart
  lib/core/data/models/dto/product_dto.dart
  lib/core/data/models/dto/review_dto.dart
  lib/feature/product/presentation/widgets/product_detail_bottom.dart
  lib/feature/product/presentation/widgets/product_detail_content.dart
  lib/feature/product/presentation/widgets/product_item.dart
  lib/feature/product/presentation/widgets/product_list_content.dart
  lib/feature/product/presentation/widgets/product_review_content.dart
  lib/feature/review/data/review_repository.dart
  lib/feature/review/data/review_service.dart
  lib/feature/review/presentation/review_detail_screen.dart
  lib/feature/review/presentation/viewmodel/review_model.dart
  lib/feature/review/presentation/widgets/add_review_content.dart
  lib/feature/review/presentation/widgets/review_item.dart
  lib/feature/review/presentation/widgets/review_written_item.dart
  lib/feature/review/presentation/widgets/review_written_tab.dart
  lib/feature/review/review_module.dart
  lib/main.dart
Labels: enhancement

#96 [Feature] home 화면 아이템 리스트 출력
  lib/feature/home/presentation/widgets/home_content_products.dart
Labels: enhancement

#99 [Feature] 공지사항 api 엔드포인트 추가
  lib/core/constants/api_endpoints.dart
  lib/core/data/models/dto/toggle_favorite_response.dart
  lib/core/data/models/entity/product.dart
  lib/feature/home/data/home_service.dart
  lib/feature/home/domain/home_repository.dart
  lib/feature/home/presentation/home_screen.dart
  lib/feature/home/presentation/viewmodel/home_viewmodel.dart
  lib/feature/home/presentation/widgets/home_content_products.dart
  lib/feature/order/presentation/order_detail_screen.dart
  lib/feature/payment/payment_screen.dart
  lib/feature/payment/presentaion/widgets/payment_content.dart
  lib/feature/preference/presentation/viewmodel/preference_viewmodel.dart
  lib/feature/product/domain/product_repository_impl.dart
  lib/feature/product/domain/repository/product_repository.dart
  lib/feature/product/presentation/viewmodel/product_list_viewmodel.dart
  lib/feature/product/presentation/viewmodel/product_viewmodel.dart
  lib/feature/product/presentation/widgets/product_detail_content.dart
  lib/feature/product/presentation/widgets/product_item.dart
  lib/feature/product/presentation/widgets/product_review_content.dart
  lib/feature/review/presentation/viewmodel/review_model.dart
  lib/feature/review/presentation/widgets/add_review_content.dart
  lib/feature/search/domain/search_repository.dart
  lib/feature/search/presentation/viewmodel/search_viewmodel.dart
  lib/feature/setting/presentation/viewmodel/setting_viewmodel.dart
  lib/main.dart
Labels: enhancement

#100 [Refactor] 작성가능 탭 수정
  lib/feature/cart/data/cart_list_item.dart
  lib/feature/order/data/order_list_item.dart
  lib/feature/review/presentation/widgets/review_writable_tab.dart
  lib/feature/review/presentation/widgets/review_written_item.dart
  lib/feature/review/presentation/widgets/review_written_tab.dart
Labels: Refactor

#103 [Feature] 회원가입DTO 필드 추가
  lib/feature/auth/data/signup_response.dart
  lib/feature/auth/data/signup_response.g.dart
  lib/feature/search/data/popular/popular_keyword_dto.g.dart
Labels: enhancement

#104 [Fix] 인기검색어가 로드되지 않던 문제 해결
  lib/feature/search/data/popular/popular_keyword_dto.dart
  lib/feature/search/data/popular/popular_keyword_dto.g.dart
  lib/feature/search/data/popular/popular_options_dto.dart
  lib/feature/search/data/popular/popular_response.dart
  lib/feature/search/data/popular/popular_response.g.dart
Labels: enhancement

#105 [Feature] Cart 관련 수정
  lib/core/data/models/dto/product_dto.dart
  lib/core/data/models/entity/product.dart
  lib/feature/cart/data/cart_Item_response.dart
  lib/feature/cart/data/cart_item_request.dart
  lib/feature/cart/data/cart_list_item.dart
  lib/feature/cart/data/cart_service.dart
  lib/feature/cart/domain/cart_repository_impl.dart
  lib/feature/cart/domain/repository/cart_repository.dart
  lib/feature/cart/domian/repository/cart_repository.dart
  lib/feature/cart/presentation/cart_module.dart
  lib/feature/cart/presentation/viewmodel/cart_viewmodel.dart
  lib/feature/cart/presentation/widgets/cart_tab.dart
  lib/feature/cart/presentation/widgets/cart_tab_bar.dart
  lib/feature/home/presentation/widgets/home_content_products.dart
  lib/feature/payment/presentaion/widgets/payment_content.dart
  lib/feature/preference/data/preference_service.dart
  lib/feature/preference/presentation/widgets/preference_content_list.dart
  lib/feature/product/data/product_service.dart
  lib/feature/product/presentation/product_detail_screen.dart
  lib/feature/product/presentation/widgets/product_detail_bottom.dart
  lib/feature/product/presentation/widgets/product_detail_content.dart
  lib/feature/product/presentation/widgets/product_item.dart
Labels: enhancement

#109 [Feature] 장바구니 목록 로드, 삭제
  lib/core/constants/api_endpoints.dart
  lib/feature/cart/data/cart_Item_response.dart
  lib/feature/cart/data/cart_order_request.dart
  lib/feature/cart/data/cart_order_response.dart
  lib/feature/cart/data/cart_service.dart
  lib/feature/cart/domain/cart_repository_impl.dart
  lib/feature/cart/domain/repository/cart_repository.dart
  lib/feature/cart/presentation/viewmodel/cart_viewmodel.dart
  lib/feature/cart/presentation/widgets/cart_list_item.dart
  lib/feature/cart/presentation/widgets/cart_tab.dart
Labels: enhancement

#110 [Feature] 주문내역 api연결
  images/icon/ic_star_large_0.svg
  images/icon/ic_star_large_1.svg
  images/icon/ic_star_small_0.svg
  images/icon/ic_star_small_1.svg
  lib/app_router.dart
  lib/core/constants/app_routes.dart
  lib/core/data/models/dto/order_dto.dart
  lib/core/data/models/dto/shipping_info_dto.dart
  lib/feature/cart/presentation/cart_main_screen.dart
  lib/feature/order/data/order_product_dto.dart
  lib/feature/order/data/order_service.dart
  lib/feature/order/domain/order_repository_impl.dart
  lib/feature/order/domain/repository/order_repository.dart
  lib/feature/order/order_module.dart
  lib/feature/order/presentation/order_detail_screen.dart
  lib/feature/order/presentation/order_list_screen.dart
  lib/feature/order/presentation/viewmodel/order_detail_viewmodel.dart
  lib/feature/order/presentation/viewmodel/order_list_viewmodel.dart
  lib/feature/order/presentation/widgets/order_delivered_tab.dart
  lib/feature/order/presentation/widgets/order_list_item.dart
  lib/feature/order/presentation/widgets/order_paid_tab.dart
  lib/feature/order/presentation/widgets/order_shipping_tab.dart
  lib/feature/review/presentation/widgets/review_writable_tab.dart
Labels: enhancement

#112 [Feature] 장바구니 주문 생성 구현
  lib/feature/payment/payment_screen.dart
  lib/feature/payment/presentaion/widgets/cart_payment_content.dart
Labels: enhancement

#115 [Feature] 주문취소 및 결제정보 연동
  lib/core/data/models/dto/order_dto.dart
  lib/core/data/models/dto/shipping_info_dto.dart
  lib/feature/order/data/order_add_requset.dart
  lib/feature/order/data/order_cancel_request.dart
  lib/feature/order/data/order_product_dto.dart
  lib/feature/order/data/order_service.dart
  lib/feature/order/domain/order_repository_impl.dart
  lib/feature/order/domain/repository/order_repository.dart
  lib/feature/order/presentation/order_detail_screen.dart
  lib/feature/order/presentation/viewmodel/order_detail_viewmodel.dart
  lib/feature/order/presentation/viewmodel/order_list_viewmodel.dart
  lib/feature/order/presentation/widgets/order_delivered_tab.dart
  lib/feature/order/presentation/widgets/order_paid_tab.dart
  lib/feature/order/presentation/widgets/order_shipping_tab.dart
Labels: enhancement

#116 [Feature] 공지 알림 api 연동
  lib/core/constants/api_endpoints.dart
  lib/feature/notification/data/app_notification.dart
  lib/feature/notification/data/app_notification_list.dart
  lib/feature/notification/data/notificationDTO.dart
  lib/feature/notification/data/notification_service.dart
  lib/feature/notification/domain/notification_repository.dart
  lib/feature/notification/notification_module.dart
  lib/feature/notification/presentation/notification_screen.dart
  lib/feature/notification/presentation/viewmodel/notification_list_viewmodel.dart
  lib/feature/notification/presentation/viewmodel/notification_viewmodel.dart
  lib/feature/notification/presentation/widgets/notification_item.dart
  lib/main.dart
Labels: enhancement

#117 [Feature] 장바구니에서 주문 구현
  lib/core/data/models/dto/shipping_info_dto.dart
  lib/feature/order/data/order_product_dto.dart
  lib/feature/payment/domain/order_info.dart
  lib/feature/payment/payment_screen.dart
  lib/feature/payment/presentaion/widgets/cart_payment_content.dart
  lib/feature/payment/presentaion/widgets/payment_content.dart
  lib/feature/product/presentation/widgets/product_detail_bottom.dart
Labels: enhancement

#120 [Refactor] 로그아웃 기능 수정 및 코드 정리
  lib/core/data/models/dto/order_dto.dart
  lib/core/data/models/dto/product_dto.dart
  lib/core/data/network/secure_storage.dart
  lib/feature/auth/presentation/viewmodel/auth_view_model.dart
  lib/feature/auth/presentation/widgets/auth_header.dart
  lib/feature/auth/presentation/widgets/login_form.dart
  lib/feature/cart/cart_module.dart
  lib/feature/cart/data/cart_item_request.dart
  lib/feature/cart/data/cart_service.dart
  lib/feature/cart/domain/repository/cart_repository.dart
  lib/feature/home/domain/home_repository.dart
  lib/feature/home/presentation/home_screen.dart
  lib/feature/home/presentation/widgets/home_content_products.dart
  lib/feature/mypage/presentation/widgets/mypage_content_menu_list.dart
  lib/feature/mypage/presentation/widgets/mypage_content_user_card.dart
  lib/feature/notification/presentation/viewmodel/notification_list_viewmodel.dart
  lib/feature/order/domain/order_repository_impl.dart
  lib/feature/order/domain/repository/order_repository.dart
  lib/feature/order/order_module.dart
  lib/feature/order/presentation/order_detail_screen.dart
  lib/feature/order/presentation/viewmodel/order_list_viewmodel.dart
  lib/feature/order/presentation/widgets/order_list_item.dart
  lib/feature/payment/presentaion/widgets/payment_bottom.dart
  lib/feature/payment/presentaion/widgets/payment_complete_content.dart
  lib/feature/preference/presentation/viewmodel/preference_viewmodel.dart
  lib/feature/product/data/product_service.dart
  lib/feature/product/domain/product_repository_impl.dart
  lib/feature/product/domain/repository/product_repository.dart
  lib/feature/product/presentation/product_detail_screen.dart
  lib/feature/product/presentation/viewmodel/product_viewmodel.dart
  lib/feature/product/presentation/widgets/product_detail_bottom.dart
  lib/feature/product/presentation/widgets/product_detail_content.dart
  lib/feature/product/presentation/widgets/product_navigation.dart
  lib/feature/product/presentation/widgets/product_review_content.dart
  lib/feature/product/product_module.dart
  lib/feature/review/presentation/widgets/add_review_content.dart
  lib/feature/review/presentation/widgets/review_written_tab.dart
  lib/feature/search/presentation/widgets/search_content_searchbar.dart
  lib/feature/setting/data/setting_service.dart
  lib/feature/setting/presentation/viewmodel/setting_viewmodel.dart
  lib/main.dart
Labels: Refactor

#123 [Feature] 장바구니 결제 추가
  lib/feature/order/data/order_service.dart
  lib/feature/payment/payment_screen.dart
  lib/feature/payment/presentaion/widgets/cart_payment_content.dart
Labels: enhancement

#126 Feature/payment
  lib/feature/cart/data/cart_order_response.dart
  lib/feature/cart/presentation/cart_main_screen.dart
  lib/feature/cart/presentation/viewmodel/cart_viewmodel.dart
  lib/feature/cart/presentation/widgets/cart_tab.dart
  lib/feature/payment/payment_screen.dart
  lib/feature/payment/presentaion/widgets/cart_payment_content.dart
  lib/feature/payment/presentaion/widgets/payment_complete_content.dart
  lib/feature/product/presentation/widgets/product_detail_bottom.dart
  lib/feature/setting/presentation/viewmodel/setting_viewmodel.dart
Labels: enhancement

#130 [Refactor] 상품 디테일 화면 ui 수정 등
  lib/feature/home/presentation/widgets/home_content_products.dart
  lib/feature/mypage/presentation/widgets/mypage_recent_content_list.dart
  lib/feature/preference/presentation/widgets/preference_content_list.dart
  lib/feature/product/presentation/widgets/product_detail_content.dart
  lib/feature/setting/presentation/widgets/user_info_tab.dart
Labels: Refactor

#131 [Refactor] cart 리스트 화면 UI 및 선택 이벤트 수정
  lib/feature/cart/presentation/widgets/cart_list_item.dart
Labels: Refactor

#136 [Refactor] 알림창 버그 픽스
  lib/feature/cart/presentation/widgets/cart_list_item.dart
  lib/feature/notification/presentation/notification_screen.dart
Labels: Refactor
